USE geddit;

LOAD DATA LOCAL INFILE 'user.csv'
INTO TABLE users
FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(username, email, password);

LOAD DATA LOCAL INFILE 'post.csv'
INTO TABLE posts
FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(userID, title, content);

LOAD DATA LOCAL INFILE 'comment.csv'
INTO TABLE comments
FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(postID, userID, content);
